services:
  - type: web
    name: prepmind-ai-api
    runtime: docker
    dockerfilePath: ./deployment/Dockerfile.backend
    plan: free

    healthCheckPath: /health

    envVars:
      - key: GEMINI_API_KEY
        sync: false

      - key: SEARCH_BACKEND
        value: "tfidf"

      - key: GEMINI_MODEL
        value: "gemini-2.5-flash"

      - key: TOP_K_RESULTS
        value: "5"

      - key: HF_HUB_DISABLE_SYMLINKS_WARNING
        value: "1"